run:
  name: "portfolio_5pct_threshold"
  description: "Optimized portfolio with 5% threshold - more frequent rebalancing"
  mode: "portfolio"

data:
  timeframe: "1h"
  days: 2977  # 8+ years

portfolio:
  assets:
    - symbol: "BTC/USDT"
      weight: 0.40
    - symbol: "ETH/USDT"
      weight: 0.30
    - symbol: "SOL/USDT"
      weight: 0.15
    - symbol: "BNB/USDT"
      weight: 0.15

  rebalancing:
    enabled: true
    threshold: 0.05  # LOWERED from 15% to 5%
    rebalance_method: "threshold"
    min_rebalance_interval_hours: 24
    use_momentum_filter: false
    momentum_lookback_days: 30

capital:
  initial_capital: 10000.0

costs:
  commission: 0.001
  slippage: 0.0005

output:
  directory: "results_5pct"
  save_trades: true
  save_equity_curve: true

logging:
  level: "INFO"
  save_to_file: true
