run:
  name: "portfolio_hybrid_monthly"
  description: "Hybrid approach - monthly calendar + 10% threshold with momentum filter"
  mode: "portfolio"

data:
  timeframe: "1h"
  days: 2977  # 8+ years

portfolio:
  assets:
    - symbol: "BTC/USDT"
      weight: 0.40
    - symbol: "ETH/USDT"
      weight: 0.30
    - symbol: "SOL/USDT"
      weight: 0.15
    - symbol: "BNB/USDT"
      weight: 0.15

  rebalancing:
    enabled: true
    threshold: 0.10  # Trigger if >10% deviation
    rebalance_method: "hybrid"  # Calendar + threshold
    calendar_period_days: 30  # Monthly rebalancing
    min_rebalance_interval_hours: 24
    use_momentum_filter: true  # Avoid rebalancing in strong trends
    momentum_lookback_days: 30

capital:
  initial_capital: 10000.0

costs:
  commission: 0.001
  slippage: 0.0005

output:
  directory: "results_hybrid"
  save_trades: true
  save_equity_curve: true

logging:
  level: "INFO"
  save_to_file: true
